eriga/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls')),
]+static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

admin.site.site_header = "Eriga Administration"
admin.site.site_title = "Eriga  Admin Portal"
admin.site.index_title = "Welcome to Eriga Admin Portal"

web/urls.py
from django.urls import path
from . import views

app_name='web'

urlpatterns = [
    path('',views.home,name='home'),
    path('servicesingle',views.servicesingle,name='servicesingle'),
    path('productsingle',views.productsingle,name='productsingle'),
    path('contact',views.contact,name='contact'),
    path('about',views.about,name='about'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('checkout',views.checkout,name='checkout'),
    # path('about',views.about,name='about'),

]
   

web/models.py
from django.db import models

# Create your models here.

web/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
def home(request):
    return render(request,"web/home.html")


def servicesingle(request):
    return render(request,"web/servicesingle.html")


def productsingle(request):
    return render(request,"web/productsingle.html")

def contact(request):
    return render(request,"web/contact.html")

def about(request):
    return render(request,"web/about.html")

def wishlist(request):
    return render(request,"web/wishlist.html")

def checkout(request):
    return render(request,"web/checkout.html")

templates/web/contact.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}


  <main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow">Home</a>
                <span></span> Pages
                <span></span> Contact us
            </div>
        </div>
    </div>
    <section class="hero-2 bg-green">
        <div class="hero-content">
            <div class="container">
                <div class="text-center">
                    <h4 class="text-brand mb-20">Get in touch</h4>
                    <h1 class="mb-20 wow fadeIn animated font-xxl fw-900">
                        Let's Talk About <br>Your <span class="text-style-1">Idea</span>
                    </h1>
                    <p class="w-50 m-auto mb-50 wow fadeIn animated">Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum quam eius placeat, a quidem mollitia at accusantium reprehenderit pariatur provident nam ratione incidunt magnam sequi.</p>
                    <p class="wow fadeIn animated">
                        <a class="btn btn-brand btn-lg font-weight-bold text-white border-radius-5 btn-shadow-brand hover-up" href="page-about.html">About Us</a>
                        <a class="btn btn-outline btn-lg btn-brand-outline font-weight-bold text-brand bg-white text-hover-white ml-15 border-radius-5 btn-shadow-brand hover-up">Support Center</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="section-border pt-50 pb-50">
        <div class="container">
            <div id='map-panes' class="leaflet-map mb-50"></div>
            <div class="row">
                <div class="col-md-4 mb-4 mb-md-0">
                    <h4 class="mb-15 text-brand">Office</h4>
                    205 North Michigan Avenue, Suite 810<br>
                    Chicago, 60601, USA<br>
                    <abbr title="Phone">Phone:</abbr> (123) 456-7890<br>
                    <abbr title="Email">Email: </abbr><a href="http://wp.alithemes.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="33505c5d475250477376455241521d505c5e">[email&#160;protected]</a><br>
                    <a class="btn btn-outline btn-sm btn-brand-outline font-weight-bold text-brand bg-white text-hover-white mt-20 border-radius-5 btn-shadow-brand hover-up"><i class="fi-rs-marker mr-10"></i>View map</a>
                </div>
                <div class="col-md-4 mb-4 mb-md-0">
                    <h4 class="mb-15 text-brand">Studio</h4>
                    205 North Michigan Avenue, Suite 810<br>
                    Chicago, 60601, USA<br>
                    <abbr title="Phone">Phone:</abbr> (123) 456-7890<br>
                    <abbr title="Email">Email: </abbr><a href="http://wp.alithemes.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="1f7c70716b7e7c6b5f5a697e6d7e317c7072">[email&#160;protected]</a><br>
                    <a class="btn btn-outline btn-sm btn-brand-outline font-weight-bold text-brand bg-white text-hover-white mt-20 border-radius-5 btn-shadow-brand hover-up"><i class="fi-rs-marker mr-10"></i>View map</a>
                </div>
                <div class="col-md-4">
                    <h4 class="mb-15 text-brand">Shop</h4>
                    205 North Michigan Avenue, Suite 810<br>
                    Chicago, 60601, USA<br>
                    <abbr title="Phone">Phone:</abbr> (123) 456-7890<br>
                    <abbr title="Email">Email: </abbr><a href="http://wp.alithemes.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="dab9b5b4aebbb9ae9a9facbba8bbf4b9b5b7">[email&#160;protected]</a><br>
                    <a class="btn btn-outline btn-sm btn-brand-outline font-weight-bold text-brand bg-white text-hover-white mt-20 border-radius-5 btn-shadow-brand hover-up"> <i class="fi-rs-marker mr-10"></i> View map</a>
                </div>
            </div>
        </div>
    </section>
    <section class="pt-50 pb-50">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-10 m-auto">
                    <div class="contact-from-area padding-20-row-col wow FadeInUp">
                        <h3 class="mb-10 text-center">Drop Us a Line</h3>
                        <p class="text-muted mb-30 text-center font-sm">Lorem ipsum dolor sit amet consectetur.</p>
                        <form class="contact-form-style text-center" id="contact-form" action="#" method="post">
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="input-style mb-20">
                                        <input name="name" placeholder="First Name" type="text">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="input-style mb-20">
                                        <input name="email" placeholder="Your Email" type="email">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="input-style mb-20">
                                        <input name="telephone" placeholder="Your Phone" type="tel">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="input-style mb-20">
                                        <input name="subject" placeholder="Subject" type="text">
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12">
                                    <div class="textarea-style mb-30">
                                        <textarea name="message" placeholder="Message"></textarea>
                                    </div>
                                    <button class="submit submit-auto-width" type="submit">Send message</button>
                                </div>
                            </div>
                        </form>
                        <p class="form-messege"></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>


{% endblock %}

templates/web/partials/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>Eriga</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'web/imgs/theme/favicon.svg' %}">
    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static 'web/css/maind6c3.css'%}">
</head>

<body>
    <!-- Quick view -->
    
    {% include 'web/partials/header.html' %}


      {% block content %}
      {% endblock %}
       
    {% include 'web/partials/footer.html' %}
    <!-- Preloader Start -->
    <!-- <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="text-center">
                    <h5 class="mb-5">Now Loading</h5>
                    <div class="loader">
                        <div class="bar bar1"></div>
                        <div class="bar bar2"></div>
                        <div class="bar bar3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
    <!-- Vendor JS-->
    <script src="{% static 'web/js/vendor/modernizr-3.6.0.min.js' %}"></script>
    <script src="{% static 'web/js/vendor/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'web/js/vendor/jquery-migrate-3.3.0.min.js' %}"></script>
    <script src="{% static 'web/js/vendor/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'web/js/plugins/slick.js' %}"></script>
    <script src="{% static 'web/js/plugins/jquery.syotimer.min.js' %}"></script>
    <script src="{% static 'web/js/plugins/wow.js' %}"></script>
    <script src="{% static 'web/js/plugins/jquery-ui.js' %}"></script>
    <script src="{% static 'web/js/plugins/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'web/js/plugins/magnific-popup.js' %}"></script>
    <script src="{% static 'web/js/plugins/select2.min.js' %}"></script>
    <script src="{% static 'web/js/plugins/waypoints.js' %}"></script>
    <script src="{% static 'web/js/plugins/counterup.js' %}"></script>
    <script src="{% static 'web/js/plugins/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'web/js/plugins/images-loaded.js' %}"></script>
    <script src="{% static 'web/js/plugins/isotope.js' %}"></script>
    <script src="{% static 'web/js/plugins/scrollup.js' %}"></script>
    <script src="{% static 'web/js/plugins/jquery.vticker-min.js' %}"></script>
    <script src="{% static 'web/js/plugins/jquery.theia.sticky.js' %}"></script>
    <script src="{% static 'web/js/plugins/jquery.elevatezoom.js' %}"></script>
    <!-- Template  JS -->
    <script src="{% static 'web/js/maind6c3.js' %}"></script>
    <script src="{% static 'web/js/shopd6c3.js' %}"></script>
</body>

</html>

templates/web/partials/footer.html
{% load static %}

<footer class="main">
    <section class="newsletter p-30 text-white wow fadeIn animated">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-7 mb-md-3 mb-lg-0">
                    <div class="row align-items-center">
                        <div class="col flex-horizontal-center">
                            <img class="icon-email" src="{% static 'web/imgs/theme/icons/icon-email.svg' %}" alt="">
                            <h4 class="font-size-20 mb-0 ml-3">Sign up to Newsletter</h4>
                        </div>
                        <div class="col my-4 my-md-0 des">
                            <h5 class="font-size-15 ml-4 mb-0">...and receive <strong>$25 coupon for first shopping.</strong></h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <!-- Subscribe Form -->
                    <form class="form-subcriber d-flex wow fadeIn animated">
                        <input type="email" class="form-control bg-white font-small" placeholder="Enter your email">
                        <button class="btn bg-dark text-white" type="submit">Subscribe</button>
                    </form>
                    <!-- End Subscribe Form -->
                </div>
            </div>
        </div>
    </section>
    <section class="section-padding footer-mid">
        <div class="container pt-15 pb-20">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="widget-about font-md mb-md-5 mb-lg-0">
                        <div class="logo logo-width-1 wow fadeIn animated">
                            <a href="{% url 'web:home' %}"><img src="{% static 'web/imgs/theme/logo.svg' %}" alt="logo"></a>
                        </div>
                        <h5 class="mt-20 mb-10 fw-600 text-grey-4 wow fadeIn animated">Contact</h5>
                        <p class="wow fadeIn animated">
                            <strong>Address: </strong>562 Wellington Road, Street 32, San Francisco
                        </p>
                        <p class="wow fadeIn animated">
                            <strong>Phone: </strong>+01 2222 365 /(+91) 01 2345 6789
                        </p>
                        <p class="wow fadeIn animated">
                            <strong>Hours: </strong>10:00 - 18:00, Mon - Sat
                        </p>
                        <h5 class="mb-10 mt-30 fw-600 text-grey-4 wow fadeIn animated">Follow Us</h5>
                        <div class="mobile-social-icon wow fadeIn animated mb-sm-5 mb-md-0">
                            <a href="#"><img src="{% static 'web/imgs/theme/icons/icon-facebook.svg' %}" alt=""></a>
                            <a href="#"><img src="{% static 'web/imgs/theme/icons/icon-twitter.svg' %}" alt=""></a>
                            <a href="#"><img src="{% static 'web/imgs/theme/icons/icon-instagram.svg' %}" alt=""></a>
                            <a href="#"><img src="{% static 'web/imgs/theme/icons/icon-pinterest.svg' %}" alt=""></a>
                            <a href="#"><img src="{% static 'web/imgs/theme/icons/icon-youtube.svg' %}" alt=""></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3">
                    <h5 class="widget-title wow fadeIn animated">About</h5>
                    <ul class="footer-list wow fadeIn animated mb-sm-5 mb-md-0">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Delivery Information</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms &amp; Conditions</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Support Center</a></li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-3">
                    <h5 class="widget-title wow fadeIn animated">My Account</h5>
                    <ul class="footer-list wow fadeIn animated">
                        <li><a href="#">Sign In</a></li>
                        <li><a href="#">View Cart</a></li>
                        <li><a href="#">My Wishlist</a></li>
                        <li><a href="#">Track My Order</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Order</a></li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <h5 class="widget-title wow fadeIn animated">Install App</h5>
                    <div class="row">
                        <div class="col-md-8 col-lg-12">
                            <p class="wow fadeIn animated">From App Store or Google Play</p>
                            <div class="download-app wow fadeIn animated">
                                <a href="#" class="hover-up mb-sm-4 mb-lg-0"><img class="active" src="{% static 'web/imgs/theme/app-store.jpg' %}" alt=""></a>
                                <a href="#" class="hover-up"><img src="{% static 'web/imgs/theme/google-play.jpg' %}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-12 mt-md-3 mt-lg-0">
                            <p class="mb-20 wow fadeIn animated">Secured Payment Gateways</p>
                            <img class="wow fadeIn animated" src="{% static 'web/imgs/theme/payment-method.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="container pb-20 wow fadeIn animated">
        <div class="row">
            <div class="col-12 mb-20">
                <div class="footer-bottom"></div>
            </div>
            <div class="col-lg-6">
                <p class="float-md-left font-sm text-muted mb-0">&copy; 2022, <strong class="text-brand">Evara</strong> - HTML Ecommerce Template </p>
            </div>
            <div class="col-lg-6">
                <p class="text-lg-end text-start font-sm text-muted mb-0">
                    Designed by <a href="http://alithemes.com/" target="_blank">Alithemes.com</a>. All rights reserved
                </p>
            </div>
        </div>
    </div>
</footer>

templates/web/servicesingle.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}


<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'web:home' %}" rel="nofollow">Home</a>
                <span></span> Blog
                <span></span> Services
            </div>
        </div>
    </div>
    <section class="mt-50 mb-50">
        <div class="container custom">
            <div class="row">
                <div class="col-lg-12">
                    <div class="single-page pr-30">
                        <div class="single-header style-2">
                            <h1 class="mb-30">Best smartwatch 2022: the top wearables you can buy today</h1>
                            <div class="single-header-meta">
                                <div class="entry-meta meta-1 font-xs mt-15 mb-15">
                                    <span class="post-by">By <a href="#">Jonh</a></span>
                                    <span class="post-on has-dot">9 April 2020</span>
                                    <span class="time-reading has-dot">8 mins read</span>
                                    <span class="hit-count  has-dot">29k Views</span>
                                </div>
                                <div class="social-icons single-share">
                                    <ul class="text-grey-5 d-inline-block">
                                        <li><strong class="mr-10">Share this:</strong></li>
                                        <li class="social-facebook"><a href="#"><img src="{% static 'web/imgs/theme/icons/icon-facebook.svg' %}" alt=""></a></li>
                                        <li class="social-twitter"> <a href="#"><img src="{% static 'web/imgs/theme/icons/icon-twitter.svg' %}" alt=""></a></li>
                                        <li class="social-instagram"><a href="#"><img src="{% static 'web/imgs/theme/icons/icon-instagram.svg' %}" alt=""></a></li>
                                        <li class="social-linkedin"><a href="#"><img src="{% static 'web/imgs/theme/icons/icon-pinterest.svg' %}" alt=""></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <figure class="single-thumbnail">
                            <img src="https://images.unsplash.com/photo-1517048676732-d65bc937f952?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="">
                        </figure>
                        <div class="single-content">
                            <p>The best smartwatch needs to be able to monitor your health, track your location when exercising, offer a variety of other apps that you wouldn't normally see on your smartphone, sport good battery life and, perhaps most importantly, have an affordable price.</p>
                            <p>We've reviewed and ranked all of the best smartwatches on the market right now, and we've made a definitive list of the top 10 devices you can buy today. One of the 10 picks below may just be your perfect next smartwatch.</p>
                            <p>Those top-end wearables span from the Apple Watch to Fitbits, Garmin watches to Tizen-sporting Samsung watches. There's also Wear OS which is Google's own wearable operating system in the vein of Apple's watchOS - you’ll see it show up in a lot of these devices.</p>
                            <p>Throughout our review process, we look at the design, features, battery life, spec, price and more for each smartwatch, rank it against the competition and enter it into the list you'll find below.</p>
                            <h4>1. Apple Watch SE</h4>
                            <ul class="mb-20">
                                <li>Updated content on a regular basis</li>
                                <li>Secure &amp; hassle-free payment</li>
                                <li>1-click checkout</li>
                                <li>Easy access &amp; smart user dashboard</li>
                            </ul>
                            <h4>2. Samsung Galaxy Watch 3</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque esse eos minima. Eius quo autem impedit quibusdam maiores, voluptatum quae sunt sit nisi voluptatem sed, esse quisquam labore, at est!</p>
                            <table class="font-md">
                                <tbody>
                                    <tr class="stand-up">
                                        <th>Stand Up</th>
                                        <td>
                                            <p>35″L x 24″W x 37-45″H(front to back wheel)</p>
                                        </td>
                                    </tr>
                                    <tr class="folded-wo-wheels">
                                        <th>Folded (w/o wheels)</th>
                                        <td>
                                            <p>32.5″L x 18.5″W x 16.5″H</p>
                                        </td>
                                    </tr>
                                    <tr class="folded-w-wheels">
                                        <th>Folded (w/ wheels)</th>
                                        <td>
                                            <p>32.5″L x 24″W x 18.5″H</p>
                                        </td>
                                    </tr>
                                    <tr class="door-pass-through">
                                        <th>Door Pass Through</th>
                                        <td>
                                            <p>24</p>
                                        </td>
                                    </tr>
                                    <tr class="frame">
                                        <th>Frame</th>
                                        <td>
                                            <p>Aluminum</p>
                                        </td>
                                    </tr>
                                    <tr class="weight-wo-wheels">
                                        <th>Weight (w/o wheels)</th>
                                        <td>
                                            <p>20 LBS</p>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <h4>3. Apple Watch 6</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque esse eos minima. Eius quo autem impedit quibusdam maiores, voluptatum quae sunt sit nisi voluptatem sed, esse quisquam labore, at est!</p>
                            <ul class="product-more-infor mb-30">
                                <li><span>Type Of Packing</span> Bottle</li>
                                <li><span>Color</span> Green, Pink, Powder Blue, Purple</li>
                                <li><span>Quantity Per Case</span> 100ml</li>
                                <li><span>Ethyl Alcohol</span> 70%</li>
                                <li><span>Piece In One</span> Carton</li>
                            </ul>
                            <h4>4. Fitbit Versa 3</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque esse eos minima. Eius quo autem impedit quibusdam maiores, voluptatum quae sunt sit nisi voluptatem sed, esse quisquam labore, at est!</p>
                            <div class="banner-img banner-big wow fadeIn f-none  mb-30  animated">
                                <img class="border-radius-10" src="{% static 'web/imgs/banner/banner-4.png' %}" alt="">
                                <div class="banner-text">
                                    <h6 class="mb-15 mt-40">Repair Services</h6>
                                    <h5 class="fw-600 mb-20">We're an Apple <br>Authorised Service Provider</h5>
                                </div>
                            </div>
                            <h4>5. Samsung Galaxy Watch Active 2</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque esse eos minima. Eius quo autem impedit quibusdam maiores, voluptatum quae sunt sit nisi voluptatem sed, esse quisquam labore, at est!</p>
                            <ul class="product-more-infor mt-30">
                                <li><span>Type Of Packing</span> Bottle</li>
                                <li><span>Color</span> Green, Pink, Powder Blue, Purple</li>
                                <li><span>Quantity Per Case</span> 100ml</li>
                                <li><span>Ethyl Alcohol</span> 70%</li>
                                <li><span>Piece In One</span> Carton</li>
                            </ul>
                        </div>
                        <div class="entry-bottom mt-50 mb-30 wow fadeIn  animated" style="visibility: visible; animation-name: fadeIn;">
                            <div class="tags w-50 w-sm-100">
                                <a href="#" rel="tag" class="hover-up btn btn-sm btn-rounded mr-10">deer</a>
                                <a href="#" rel="tag" class="hover-up btn btn-sm btn-rounded mr-10">nature</a>
                                <a href="#" rel="tag" class="hover-up btn btn-sm btn-rounded mr-10">conserve</a>
                            </div>
                            <div class="social-icons single-share">
                                <ul class="text-grey-5 d-inline-block">
                                    <li><strong class="mr-10">Share this:</strong></li>
                                    <li class="social-facebook"><a href="#"><img src="{% static 'web/imgs/theme/icons/icon-facebook.svg' %}" alt=""></a></li>
                                    <li class="social-twitter"> <a href="#"><img src="{% static 'web/imgs/theme/icons/icon-twitter.svg' %}" alt=""></a></li>
                                    <li class="social-instagram"><a href="#"><img src="{% static 'web/imgs/theme/icons/icon-instagram.svg' %}" alt=""></a></li>
                                    <li class="social-linkedin"><a href="#"><img src="{% static 'web/imgs/theme/icons/icon-pinterest.svg' %}" alt=""></a></li>
                                </ul>
                            </div>
                        </div>
                       
                        <div class="comment-form">
                            <h4 class="mb-15">Request to Buy</h4>
                            
                            <div class="row">
                                <div class="col-lg-8 col-md-12">
                                    <form class="form-contact comment_form" action="#" id="commentForm">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <textarea class="form-control w-100" name="comment" id="comment" cols="30" rows="9" placeholder="Write Comment"></textarea>
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <input class="form-control" name="name" id="name" type="text" placeholder="Name">
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <input class="form-control" name="email" id="email" type="email" placeholder="Email">
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <input class="form-control" name="website" id="website" type="text" placeholder="Website">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="button button-contactForm">Sent Request</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </section>
</main>

{% endblock %}